config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  
   root 'application#index'
   get 'docs' => 'application#docs'
   get 'find_page' => 'pages#find_page'
   get 'page_not_found' => 'application#page_not_found'
   get 'my_flags' => 'application#my_flags'
   get 'priorities' => 'areas#index'
   post 'pages/toggle_page_vote' => 'pages#toggle_page_vote'
   post 'pages/toggle_reviewed' => 'pages#toggle_reviewed'
   post 'comments/new' => 'comments#new'
   post 'pages/remove_tag' => 'pages#remove_tag'
   post 'pages/delete_comment' => 'pages#delete_comment'
   post 'pages/set_page_risk' => 'pages#set_page_risk'
   post 'pages/set_page_priority' => 'pages#set_page_priority'
   post 'areas/set_area_priority' => 'areas#set_area_priority'
   post 'areas/set_area_frequency' => 'areas#set_area_frequency'
   post 'areas/set_writer_coverage' => 'areas#set_writer_coverage'
   post 'areas/set_area_support' => 'areas#set_area_support'
   post 'areas/set_area_work' => 'areas#set_area_work'
   post 'pages/set_page_owner' => 'pages#set_page_owner'
   post 'pages/content_reimport' => 'pages#content_reimport'
   post 'pages/add_to_tag_list' => 'pages#add_to_tag_list'
   get '/tags/' => 'pages#tags'
   get '/tags/:tag_name' => 'pages#tag'
   get '/index' => 'application#indexed_words'
   get '/users/' => 'users#index'
   get '/missing_pages' => 'pages#missing_pages'
   match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
   resources :repos
   resources :areas
   resources :pages, shallow: true do
         get :autocomplete_tag_name, :on => :collection    
   end
   resources :projects do
     resources :versions 
   end
   
   resources :comments

end

app/views/pages/_comment_edit_modal.html.haml
%div.modal.fade{:id => "comment_edit_#{this_comment.id}", :role => "dialog"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{"data-dismiss" => "modal"}
          &times;
        %h4.modal-title
          %span.glyphicon.glyphicon-comment &nbsp;
          Edit Your Comment
        %p.small
          Feel free to use a little Markdown. Not too much.
      %div.modal-body
        = simple_form_for [this_comment], :remote => true do  |f|
          = f.input :content, label: false, :input_html => {:rows => 10,:autofocus => 'autofocus'}, :value => this_comment.content
          = f.button :submit, "Save Comment", :html => {"data-dismiss" => "modal"}, :class => "btn btn-primary"
        %br
        %div.modal-footer

app/views/pages/_page_comments.html.haml
- if @page.comments.size > 0
  - @page.comments.each do |c|
    .panel.small.panel-default
      .panel-heading
        %b
          Comment by
          = c.user.handle
      .panel-body
        != c.rendered_content
      .panel-footer.small
        Posted
        = c.created_at.strftime('%Y-%m-%d at %I:%M %p')
        %br
        %br

        - if current_user
          - if c.user_id == current_user.id
            = render :partial => "pages/comment_edit_modal", :locals => {:this_comment => c}
            %button.btn.btn-primary.btn-xs{:id => "comment_edit_button_#{c.id}", "data-toggle" => "modal", "data-target" => "#comment_edit_#{c.id}"}
              Edit
          - if c.user_id == current_user.id || current_user.try(:admin?)
            = link_to 'Delete', pages_delete_comment_path(:id => c.id, :page => @page.id), :method => :post, :remote => true, :class => 'btn btn-danger btn-xs pull-right'
            %br
            %br
  
        

  

app/views/pages/_page_owner_button.html.haml
- if current_user.try(:admin?)
  .btn-group.btn-group-xs
    %button.btn.btn-default
      - if @page.user.nil?
        Set Owner
      - else
        = link_to @page.user.handle, @page.user
    %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
      %span.caret
    %ul.dropdown-menu{:role => "menu"}
      - User.admins.each do |u|
        %li
          = link_to pages_set_page_owner_path(:page_id => @page.id, :user_id => u.id), :remote => true, :method => :post do
            = u.handle
      %li.divider
      %li
        = link_to pages_set_page_owner_path(:page_id => @page.id, :user_id => current_user.id, :action_id => "disown"), :remote => true, :method => :post do
          No Owner
    
        
 

app/views/pages/_page_tools.html.haml
.btn-group.btn-group-xs
  - unless @page.previous_page.nil?
    = link_to page_path(@page.previous_page), :class => "btn btn-primary" do
      %span.glyphicon.glyphicon-step-backward
      &nbsp;  
  %button.btn.btn-primary.btn-sm{:id => "composition_button", "data-toggle" => "tooltip", "data-placement" => "top", :title => "Toggle all but ordered lists and pre/code blocks" }
    &nbsp;  
    %span{:id => "content-button", :class => "glyphicon glyphicon-eye-close"}
    &nbsp;    
  - unless @page.next_page.nil?
    &nbsp;  
    = link_to page_path(@page.next_page), :class => "btn btn-sm btn-primary" do
      &nbsp;  
      %span.glyphicon.glyphicon-step-forward

.btn-group
  %div{:id => "priority-button-#{@page.id}"}
    = render :partial => "priority_button", :locals => {:page_id => @page.id}
.btn-group
  %div{:id => "risk-button-#{@page.id}"}
    = render :partial => "risk_button", :locals => {:page_id => @page.id}

- if current_user && @page.has_owner && @page.user_id == current_user.id 
  .btn-group
    %div{:style => "float:left;width:auto;margin-left:.5em;", :id => 'review_button'}
      = render :partial => "reviewed_button"

app/views/pages/_pages_table.html.haml
%table.table.sortable
  %thead 
    %tr
      %th
        Reviewed
      %th
        Priority
      %th
        Risk
      %th
        Page
      %th
        Tags

  %tbody        
    - pages.each do |page|
      = render :partial => "pages/pages_row", :locals => {:page => page}

    
  

app/views/pages/_reviewed_button.html.haml
- if @page.reviewed 
  = button_to 'Mark Unreviewed', {:controller => 'pages', :action => :toggle_reviewed, :page_id => @page.id}, {:class => 'btn-danger btn btn-xs', :remote => true, :id => 'page_review_button'} 
- else
  = button_to 'Mark Reviewed', {:controller => 'pages', :action => :toggle_reviewed, :page_id => @page.id}, {:class => 'btn-success btn btn-xs', :remote => true, :id => 'page_review_button'} 

app/views/pages/_tags_modal.html.haml
%div.modal.fade{:id => "tagsModal", :role => "dialog", 'data-backdrop' => 'false'}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{"data-dismiss" => "modal"}
          &times;
        %h4.modal-title
          %span.glyphicon.glyphicon-tags &nbsp;
          Tags

      %div.modal-body
        = simple_form_for @page,  :remote => true, 
          :url => url_for(:action => 'add_to_tag_list', :controller => 'pages'), html: { class: "form-horizontal"}, :method => 'post'  do  |f|
          .form-group.form-group-sm.ui-front
            .col-sm-10.col-sm-offset-1
              = f.autocomplete_field :tag_list, autocomplete_tag_name_pages_path, "data-delimiter" => ', ', :class => 'form-control input-sm', :autofocus => "autofocus", :value => nil
              = f.hidden_field :page_id, :value =>  @page.id
              %span.help-block.small.muted-text
                Comma-delimited list of tags (e.g. "foo,bar,baz"). 
          .control-group.col-sm-offset-1
            = f.button :submit, "Save Tags", :html => {"data-dismiss" => "modal"}, :class => "btn btn-primary btn-xs"
      %div.modal-footer

app/views/pages/content_reimport.html.haml
.btn-group
  =link_to pages_reimport_html_path(@page), :remote => true, :method => :post do
    %button.btn-primary.btn-xs

app/views/pages/content_reimport.js.haml
$("#imported_content").effect("highlight",1000);
$("#imported_content").html("#{j raw(@page.content)}");
$("#elements").html("#{j render(:partial => 'pages/elements_panel')}");

app/views/pages/tag.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li
    = link_to "Tags", tags_path
  %li.inactive
    = @tag

%table.table.sortable
  %thead 
    %tr
      %th
        Reviewed
      %th{:"data-defaultsort" => "desc"}
        Priority
      %th
        Risk
      %th
        Page
      %th
        Tags
  %tbody        
    - @pages.each do |page|
      = render :partial => "pages/pages_row", :locals => {:page => page}
      
:javascript

app/views/pages/tags.html.haml
%ol.breadcrumb
  %li
    %a{:href => root_path}
      Home
  %li.inactive
    All Tags

%ul    
  - @tags.each do |t|
    %li
      %a{:href => "/tags/#{t.name}"}
        = t.name
      = "(#{t.taggings_count})"
      

app/views/pages/update_priority_button.js.haml
$("#priority-button-#{id}").html("#{j render(:partial => 'pages/priority_button', :locals => {:page_id => id})}");
$("#td_priority_#{id}").attr("data-value", "#{priority}");
$("#td_priority_#{id}").parent('tr').attr("data-priority", "#{priority}");
$("#priority-button-#{id}").effect("bounce",500);

app/views/pages/update_risk_button.js.haml
$("#risk-button-#{id}").html("#{j render(:partial => 'pages/risk_button', :locals => {:page_id => id})}");
$("#td_risk_#{id}").attr("data-value", "#{risk}");
$("#td_risk_#{id}").parent('tr').attr("data-risk", "#{risk}");
$("#risk-button-#{id}").effect("bounce",500);

app/views/pages/update_tags.js.haml
$('#page_tags').html("#{j render(:partial => 'pages/page_tags')}");
$('#tags_modal').html("#{j render(:partial => 'pages/tags_modal')}");
$("#page_tags").effect("bounce",500);
$('body').css('overflow', 'auto');