config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  
   root 'application#index'
   get 'docs' => 'application#docs'
   get 'find_page' => 'pages#find_page'
   get 'page_not_found' => 'application#page_not_found'
   get 'my_flags' => 'application#my_flags'
   get 'priorities' => 'areas#index'
   post 'pages/toggle_page_vote' => 'pages#toggle_page_vote'
   post 'pages/toggle_reviewed' => 'pages#toggle_reviewed'
   post 'comments/new' => 'comments#new'
   post 'pages/remove_tag' => 'pages#remove_tag'
   post 'pages/delete_comment' => 'pages#delete_comment'
   post 'pages/set_page_risk' => 'pages#set_page_risk'
   post 'pages/set_page_priority' => 'pages#set_page_priority'
   post 'areas/set_area_priority' => 'areas#set_area_priority'
   post 'areas/set_area_frequency' => 'areas#set_area_frequency'
   post 'areas/set_writer_coverage' => 'areas#set_writer_coverage'
   post 'areas/set_area_support' => 'areas#set_area_support'
   post 'areas/set_area_work' => 'areas#set_area_work'
   post 'pages/set_page_owner' => 'pages#set_page_owner'
   post 'pages/content_reimport' => 'pages#content_reimport'
   post 'pages/add_to_tag_list' => 'pages#add_to_tag_list'
   get '/tags/' => 'pages#tags'
   get '/tags/:tag_name' => 'pages#tag'
   get '/index' => 'application#indexed_words'
   get '/users/' => 'users#index'
   get '/missing_pages' => 'pages#missing_pages'
   match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
   resources :repos
   resources :areas
   resources :pages, shallow: true do
         get :autocomplete_tag_name, :on => :collection    
   end
   resources :projects do
     resources :versions 
   end
   
   resources :comments

end

app/models/project.rb
class Project < ActiveRecord::Base

 
  has_many :versions, :dependent => :destroy  
  has_many :pages, through: :versions

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :display_name,
      [:display_name, :id]
    ]
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :verify_is_admin, except: [:show, :index]

  def show
    @project = Project.friendly.find(params[:id])
    @versions = @project.versions.order(version_number: :desc)
    @title = @project.display_name
  end

  def index
    @title = "Projects"
    @projects = Project.order(display_name: :asc)

  end

  def edit
    @project = Project.friendly.find(params[:id])
    @title = "Edit #{@project.display_name}"
  end

  def update
    @project = Project.friendly.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to projects_path
    else
      render 'edit', alert: "Bad value in your edit form. Better talk to Mike."
    end
  end

  private
  def project_params
    params.require(:project).permit(:display_name, :name, :versioned, :description, :web_path)
  end

  def verify_is_admin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end

  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.haml
%ol.breadcrumb
  %li
    %a{:href => root_path}
      Home
  %li
    = link_to projects_path do
      Projects
  %li.inactive
    = @project.display_name

%br
= form_for(@project, url: project_path(:project_id => @project.id), html: { method: :patch, :class => "form-horizontal"}) do |f|

  .form-group
    = f.label "Display Name", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :display_name, :class => "form-control"
      %p.help-block
        This is the name to display in menus, etc., e.g. "Puppet Enteprise"

  .form-group
    = f.label "Content Directory", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, :class => 'form-control'
      %p.help-block
        This is the name of the directory the project lives in under /source in the repo, e.g. "pe", "puppet," etc.

  .form-group
    = f.label "Web Path", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :web_path, :class => 'form-control'
      %p.help-block
        This is the base URL for this project on the web, e.g. "https://docs.puppetlabs.com/pe"
      
  .form-group
    = f.label "Versioned?", :class => 'col-sm-2 control-label'
    .col-sm-4
      .checkbox
        %label
          = f.check_box :versioned do 
            Versioned?
        %p.help-block
          If this project has no versions (e.g. the guides directory), leave this unchecked. 

  .form-group
    = f.label "Description", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_area :description, :class => "form-control"
      %p.help-block
        Describe the project 
    
  .actions.col-sm-offset-2
    .col-sm-4
      = f.submit "Update", :class => 'btn btn-primary'

   

app/views/projects/index.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li.active
    Projects

%table.table
  %thead 
    %tr
      %th
        Project
      %th
        Versions
      %th
        Description
      - if current_user.try(:super?)
        %th
          Edit

  %tbody        

    - @projects.each do |p|
      %tr
        %td
          = link_to p.display_name, p
    
        %td
          = p.versions.count
        %td
          = p.description
        
        - if current_user.try(:super?)
          %td
            =link_to edit_project_path(p) do 
              %button.btn.btn-danger.btn-xs
                Edit

app/views/projects/show.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li
    = link_to "Projects", projects_path
  %li.active
    = @project.display_name

%table.table
  %thead
    %tr
      %th
        Version
      %th
        Published?
      %th
        Active?
      %th
        Total Pages
      %th
        High Priority Pages
      %th
        High Risk Pages
      - if current_user.try(:admin?)
        %th

  %tbody

    - @versions.each do |v|
      %tr
        %td
          = link_to project_version_path(v.project, v) do
            - if @project.versioned == false
              = "#{v.version_number} #{@project.display_name}"
            - else
              = "#{@project.display_name} #{v.version_number}"

        %td
          - if v.published?
            %span.glyphicon.glyphicon-ok.text-success
          - else
            %span.glyphicon.glyphicon-remove.text-danger
              
        %td
          - if v.active?
            %span.glyphicon.glyphicon-ok.text-success
          - else
            %span.glyphicon.glyphicon-remove.text-danger
        %td
          = v.pages.count
        %td
          = v.high_priority_pages
        %td
          = v.high_risk_pages
        - if current_user.try(:admin?)
          %td
            = link_to edit_project_version_path(v.project, v) do
              %button.btn.btn-danger.btn-xs
                Edit
          
          