config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  
   root 'application#index'
   get 'docs' => 'application#docs'
   get 'find_page' => 'pages#find_page'
   get 'page_not_found' => 'application#page_not_found'
   get 'my_flags' => 'application#my_flags'
   get 'priorities' => 'areas#index'
   post 'pages/toggle_page_vote' => 'pages#toggle_page_vote'
   post 'pages/toggle_reviewed' => 'pages#toggle_reviewed'
   post 'comments/new' => 'comments#new'
   post 'pages/remove_tag' => 'pages#remove_tag'
   post 'pages/delete_comment' => 'pages#delete_comment'
   post 'pages/set_page_risk' => 'pages#set_page_risk'
   post 'pages/set_page_priority' => 'pages#set_page_priority'
   post 'areas/set_area_priority' => 'areas#set_area_priority'
   post 'areas/set_area_frequency' => 'areas#set_area_frequency'
   post 'areas/set_writer_coverage' => 'areas#set_writer_coverage'
   post 'areas/set_area_support' => 'areas#set_area_support'
   post 'areas/set_area_work' => 'areas#set_area_work'
   post 'pages/set_page_owner' => 'pages#set_page_owner'
   post 'pages/content_reimport' => 'pages#content_reimport'
   post 'pages/add_to_tag_list' => 'pages#add_to_tag_list'
   get '/tags/' => 'pages#tags'
   get '/tags/:tag_name' => 'pages#tag'
   get '/index' => 'application#indexed_words'
   get '/users/' => 'users#index'
   get '/missing_pages' => 'pages#missing_pages'
   match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
   resources :repos
   resources :areas
   resources :pages, shallow: true do
         get :autocomplete_tag_name, :on => :collection    
   end
   resources :projects do
     resources :versions 
   end
   
   resources :comments

end

app/models/version.rb
class Version < ActiveRecord::Base
  validates :version_number, :version_directory, :branch, :presence => true
  
  belongs_to :project
  validates :project_id, :presence => true
  

  has_many :pages, :dependent => :destroy  
  has_many :comments, :through => :page

  scope :published, -> {where(:published => true)}
  
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  
  def slug_candidates
    [
      :version_number,
      [:project_name, :version_number]
    ]
  end


  def project_name
    self.project.name
  end
  
  def high_risk_pages
    self.pages.where(:risk => 3).count
  end

  def high_priority_pages
    self.pages.where(:priority => 3).count
  end

  scope :active, -> {where(:active => true)}
  scope :inactive, -> {where(:active => false)}

  def repo_base
    self.base_directory.sub(/\/.*/, "")
  end
  
   def base_directory
     "#{self.version_directory}/"
   end

  def repos_dir
    "#{Rails.root}/repos/#{self.version_directory}"
  end
   
  def public_dir
    "#{Rails.root}/public/#{self.version_directory}"
  end

  def import_files
    require 'find'
    
    Dir.chdir(self.repos_dir) do
      system("git checkout #{branch} --quiet && git pull --ff --quiet && git clean --force . --quiet")
    end
    
    Find.find(self.repos_dir) do |f|
        next unless f.match(/\.(markdown|md)\Z/)
        next if f.match(/.+?\/_(.+?)\.(markdown|md)/)
        file = File.read(f)
        begin
         src = file.match(/^(---\s*\n.*?\n?)^(---\s*$\n?)/m)
         markdown = src.post_match
         src_yaml =  YAML.load_file(f)
        rescue Exception => e
          puts e
          next
        end

       file_name = f.gsub(/#{repos_dir}/, "")

        begin
          page =  self.pages.find_or_initialize_by(:filename => file_name)
          page.title = src_yaml['title']
          page.subtitle = src_yaml['subtitle']
          page.frontmatter = src_yaml
          page.markdown_content = markdown
          page.generate_html
          page.repath_images
          page.save
          
        rescue Exception => e  
          puts "Problem with this file: #{f}\n#{e}"
          next
        end
    end
  end


  
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_filter :verify_is_admin, except: [:show, :index]
  
  def show
    @version = Version.friendly.find(params[:id])
    @title = "#{@version.project.display_name} #{@version.version_number}"
    @pages = @version.pages.order(title: :asc)
    render :template => "versions/show", :locals => {:pages => @pages}
  end
 
  def edit
    @version = Version.friendly.find(params[:id])
    @title = "Edit #{@version.project.display_name} #{@version.version_number}"
  end

  def update
    @version = Version.friendly.find(params[:id])
    if @version.update_attributes(version_params)
      redirect_to project_path(@version.project)
    else
      render 'edit', alert: "Bad value in your edit form. Better talk to Mike."
    end
  end

  private
  def version_params
    params.require(:version).permit(:project_id, :branch, :active, :version_number, :version_directory, :source_repo, :published)
  end

  def verify_is_admin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/versions/edit.html.haml
%ol.breadcrumb
  %li
    %a{:href => root_path}
      Home
  %li
    = link_to @version.project.display_name, project_path(@version.project)

  %li.inactive
    = @version.version_number

%br
= form_for(@version, url: project_version_path(:version_id => @version.id, :project_id => @version.project.id), html: { method: :patch, :class => "form-horizontal"}) do |f|

        
  .form-group
    = f.label "Version Number", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :version_number, :class => 'form-control'
      %p.help-block
        e.g. "3.8" or "4.1"
        
  .form-group
    = f.label "Version directory", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :version_directory, :class => 'form-control'
      %p.help-block
        e.g. "puppet-docs/source/puppet/4.1"

  .form-group
    = f.label "Source Repository URL", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :source_repo, :class => 'form-control'
      %p.help-block
        The GitHub URL for the source repository. 
    
  .form-group
    = f.label "Branch", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :branch, :class => 'form-control'
      %p.help-block
        The Git branch in which this version is being worked on. For pages already published, this should be "master."

  .form-group
    = f.label "Active version?", :class => 'col-sm-2 control-label'
    .col-sm-4
      .checkbox
        %label
          = f.check_box :active do 
            Active Version?
        %p.help-block
          Unchecking this box keeps the HTML and elements from being updated for this version.

  .form-group
    = f.label "Published version?", :class => 'col-sm-2 control-label'
    .col-sm-4
      .checkbox
        %label
          = f.check_box :published do 
            Published Version?
        %p.help-block
          Check to indicate that this version is published to the production docs website.

          
  .actions.col-sm-offset-2
    .col-sm-4
      = f.submit "Update", :class => 'btn btn-primary'

   

app/views/versions/index.html.haml
%h1
 = @project.display_name

%ul
  - @project.versions.each do |v|
    %li
      = v.version_number

app/views/versions/show.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li
    = link_to "Projects", projects_path
  %li
    = link_to @version.project.display_name, project_path(@version.project)
  %li.active
    = @version.version_number

%form.form-inline.text-right.form-horizontal
  .form-group
    %label
      Filter: &nbsp;
    %input.input-sm.form-control{:id => 'filter-table', :placeholder => 'Filter this table', :type => 'text'}

= render :partial => "pages/pages_table", :locals => {:pages => pages}
= render :partial => "pages/table_js.js.haml"
= render :partial => "pages/filter_table.js.haml"