config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  
   root 'application#index'
   get 'docs' => 'application#docs'
   get 'find_page' => 'pages#find_page'
   get 'page_not_found' => 'application#page_not_found'
   get 'my_flags' => 'application#my_flags'
   get 'priorities' => 'areas#index'
   post 'pages/toggle_page_vote' => 'pages#toggle_page_vote'
   post 'pages/toggle_reviewed' => 'pages#toggle_reviewed'
   post 'comments/new' => 'comments#new'
   post 'pages/remove_tag' => 'pages#remove_tag'
   post 'pages/delete_comment' => 'pages#delete_comment'
   post 'pages/set_page_risk' => 'pages#set_page_risk'
   post 'pages/set_page_priority' => 'pages#set_page_priority'
   post 'areas/set_area_priority' => 'areas#set_area_priority'
   post 'areas/set_area_frequency' => 'areas#set_area_frequency'
   post 'areas/set_writer_coverage' => 'areas#set_writer_coverage'
   post 'areas/set_area_support' => 'areas#set_area_support'
   post 'areas/set_area_work' => 'areas#set_area_work'
   post 'pages/set_page_owner' => 'pages#set_page_owner'
   post 'pages/content_reimport' => 'pages#content_reimport'
   post 'pages/add_to_tag_list' => 'pages#add_to_tag_list'
   get '/tags/' => 'pages#tags'
   get '/tags/:tag_name' => 'pages#tag'
   get '/index' => 'application#indexed_words'
   get '/users/' => 'users#index'
   get '/missing_pages' => 'pages#missing_pages'
   match '/users/:id', :to => 'users#show', :as => :user,  :via => :get
   resources :repos
   resources :areas
   resources :pages, shallow: true do
         get :autocomplete_tag_name, :on => :collection    
   end
   resources :projects do
     resources :versions 
   end
   
   resources :comments

end

app/models/area.rb
class Area < ActiveRecord::Base

  has_and_belongs_to_many :users
  markdownize! :description

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :name,
      [:name, :id],
    ]
  end


  scope :priority, ->(priority) { where("priority = ?", priority) }
  scope :writer_coverage, ->(coverage) { where("writer_coverage = ?", coverage) }

  scope :low_risk, Proc.new { |area| area.support_status == 1 }
  scope :medium_risk, Proc.new { |area| area.support_status == 2 }
  scope :high_risk, Proc.new { |area| area.support_status == 3 }
  scope :unknown_risk, Proc.new { |area| area.support_status == 0 }

  
  def self.status(status)
    areas = Area.select { |a| a.support_status == status}
    return areas
  end
    
  def self.cost(cost)
    areas = Area.select { |a| a.burden == cost }
    return areas
  end
  
  def support_status

    if self.priority == nil || self.writer_coverage == nil || self.priority == 0 
      0
    elsif self.priority > self.writer_coverage + 1
      3
    elsif self.priority > self.writer_coverage
      2
    else
      1
    end
   
  end

  def burden
    if self.writer_coverage == nil || self.support == nil 
      0
    elsif self.writer_coverage == 0 || self.support == 0
      0
    else
      self.writer_coverage + self.support
    end
  end



  def priority_narrative
    case self.priority
    when 0
      "Undetermined"
    when 1
      "Low"
    when 2
      "Medium"
    when 3
      "High"
    end
  end

  def coverage_narrative
    case self.writer_coverage
    when 0
      "no"
    when 1
      "a little"
    when 2
      "some"
    when 3
      "substantial"
    end
  end
  
  def burden_narrative
    case self.burden
    when 0
      "Unknown"
    when 1..4
      "Low"
    when 5..6
      "High"
    end
  end

  def support_narrative
    case self.support_status
    when 0
      "at Unknown Risk"
    when 1
      "at Very Little Risk"
    when 2
      "at Some Risk"
    when 3
      "at High Risk"
    end
  end


end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_filter :verify_is_super, except: [:show, :index]

  
  def index
    @areas = Area.all.order(:name)
    @title = "Documentation Capacity"
    render :template => "areas/index",
           :locals => {:areas => @areas}   
  end

  def edit
    @area = Area.friendly.find(params[:id])
    @title = "Edit #{@area.name}"
  end

  def update
    @area = Area.friendly.find(params[:id])
    if @area.update_attributes(area_params)
      redirect_to area_path(@area)
    else
      render 'edit', alert: "Bad value in your edit form. Better talk to Mike."
    end
  end

  def show
    @area = Area.friendly.find(params[:id])
  end

  
  def new
    @area = Area.new
  end

  def create
    @area = Area.new(:name => params[:area][:name],
                     :priority => params[:area][:priority],
                     :frequency => params[:area][:frequency],
                     :support => params[:area][:support],
                     :work => params[:area][:work])
    if @area.save
      respond_to do |format|
        format.html {redirect_to areas_path, :alert => "Area saved."}
      end
    end
  end


  def destroy
    @area = Area.friendly.find params[:id]
    if @area.destroy
      respond_to do |format|
        format.js {render :action => 'destroy_area.js.haml',
                          :locals => {:area_id => @area.id}}
      end
    end
  end

  def set_area_priority
    @priority = params[:priority]
    @area = Area.friendly.find(params[:area_id])
    @area.priority = @priority

    if @area.save
      respond_to do |format|
        format.js { render :action => 'update_priority_button.js.haml',
                           :locals => {:id => params[:area_id],
                                       :priority => @area.priority,
                                       :area => @area}}
        format.html 
      end
    end
  end

 def set_area_frequency
    @frequency = params[:frequency]
    @area = Area.friendly.find(params[:area_id])
    @area.frequency = @frequency

    if @area.save
      respond_to do |format|
        format.js { render :action => 'update_frequency_button.js.haml',
                           :locals => {:id => params[:area_id],
                                       :frequency => @area.frequency,
                                       :area => @area}}
        format.html 
      end
    end
 end

  def set_writer_coverage
    @writer_coverage = params[:writer_coverage]
    @area = Area.friendly.find(params[:area_id])
    @area.writer_coverage = @writer_coverage

    if @area.save
      respond_to do |format|
        format.js { render :action => 'update_writer_coverage_button.js.haml',
                           :locals => {:id => params[:area_id],
                                       :writer_coverage => @area.writer_coverage,
                                       :area => @area}}
        format.html 
      end
    end
  end

  def set_area_support
    @support = params[:support]
    @area = Area.friendly.find(params[:area_id])
    @area.support = @support

    if @area.save
      respond_to do |format|
        format.js { render :action => 'update_support_button.js.haml',
                           :locals => {:id => params[:area_id],
                                       :support => @area.support,
                                       :area => @area}}
        format.html 
      end
    end
  end

  
  private

  def area_params
    params.require(:area).permit(:area_id, :name, :priority, :work, :support, :writer_support, :description, :points, :user_ids => [])
  end
  
  def verify_is_admin
    (current_user.nil?) ? redirect_to(areas_path) : (redirect_to(areas_path) unless current_user.admin?)
  end

  def verify_is_super
    (current_user.nil?) ? redirect_to(areas_path) : (redirect_to(areas_path) unless current_user.super?)
  end
  
end

app/helpers/areas_helper.rb
module AreasHelper


  def display_label(level, property)

    case level
    when 0
      label_class = "default"
      label = "No"
    when 1
      if property == "Coverage"
        label_class = "danger"
      else
        label_class = "success"
      end
      label = "Low"
    when 2
      label_class = "warning"
      label = "Medium"
    when 3
      if property == "Coverage"
        label_class = "success"
      else
        label_class = "danger"
      end
      label = "High"
    end

    capture_haml do
      haml_tag :span, class: "label-#{label_class} label" do
        haml_concat "#{label} #{property}"
      end
    end

  end

  def burden_label(area)
    case area.burden
    when 0
      label_class = "default"
      label = "No"
    when 1..4
      label_class = "success"
      label = "Low"
    when 5..6
      label_class = "danger"
      label = "High"
    end

 capture_haml do
      haml_tag :span, class: "label-#{label_class} label" do
        haml_concat "#{label} Effort"
      end
    end

  end


  


  def support_indicator(area)
    case area.support_status
    when 0
      glyph = "glyphicon-question-sign"
      indicator_class = "muted"
    when 1
      glyph = "glyphicon-ok"
      indicator_class = "success"
    when 2
      glyph = "glyphicon-warning-sign"
      indicator_class = "warning"
    when 3
      glyph = "glyphicon-fire"
      indicator_class = "danger"
    end

     capture_haml do
       haml_tag :span, class: "glyphicon #{glyph} text-#{indicator_class}"
     end    
  end

  def burden_indicator(area)
    case area.burden
    when 0
      glyph = "glyphicon-question-sign"
      indicator_class = "muted"
    when 1..4
      glyph = "glyphicon-triangle-bottom"
      indicator_class = "success"
    # when 2..4
    #   glyph = "glyphicon-ok"
    #   indicator_class = "success"
    when 5..6
      glyph = "glyphicon-triangle-top"
      indicator_class = "danger"
    end

     capture_haml do
       haml_tag :span, class: "glyphicon #{glyph} text-#{indicator_class}"
     end    
        
  end

  def area_button(area,prop)
    area = Area.find(area)
    case prop
    when "Support"
      area_prop = area.support
    when "Priority"
      area_prop = area.priority
    when "Coverage"
      area_prop = area.writer_coverage
    end
    
    case area_prop
        when 0
          word = "No"
          btn_class = "Danger"
        when 1
          word = "Low"
          if prop == "Support"
            btn_class = "success"
          else
            btn_class ="danger"
          end
        when 2
          word = "Medium"
          btn_class = "warning"
        when 3
          word = "High"
          if prop == "Support"
            btn_class = "danger"
          else
            btn_class = "success"
          end
        else
          word = ""
          btn_class = "primary"
    end

    if area_prop == nil && current_user.try(:super?)
      word = "Set"
      disabled_state = nil
      btn_class = "default"
    elsif area_prop == nil && !current_user.try(:super?)
      word = "Unset"
      disabled_state = "disabled"
      btn_class = "default"
    elsif !current_user.try(:super?)
      disabled_state = "disabled"
    end

    if current_user.try(:super?)
      capture_haml do
        haml_tag :button,
                 :class => "btn btn-#{btn_class} dropdown-toggle btn-xs",
                 "data-toggle" => "dropdown",
                 :type => "button",
                 :disabled => disabled_state do
          haml_concat "#{word} #{prop}"
          if current_user.try(:super?)
            haml_tag :span, :class => "caret"
          end
        end
      end
    else
      capture_haml do
          haml_tag :span,
                   :class => "btn btn-#{btn_class}" do
            haml_concat "#{word} #{prop}"
        end
      end
    end
  end
  
  
end

app/views/areas/_burden_field.html.haml
- area = Area.find(area_id)
= burden_indicator(area)

app/views/areas/_frequency_button.html.haml
- levels = {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}
.btn-group.btn-group-xs
  != area_button(area_id,"Writer Coverage")
  - if current_user.try(:super?)
    %ul.dropdown-menu{:role => "menu"}
      - levels.each do |l,n|
        %li
          =link_to areas_set_area_writer_coverage_path(:area_id => area_id, :writer_coverage => n), :remote => true, :method => :post do
            = l

app/views/areas/_index_row.html.haml
- area.support_status == 0 || area.burden == 0 ? row_data = "unknown" : row_data = "known"

%tr{:id => "area_row_#{area.id}", "data-value" => row_data }

  %td{:id => "area_status_#{area.id}", "data-value" => area.support_status }
    = support_indicator(area)

  %td{"data-value" => area.name, :id => "area_name_#{area.id}"}
    = link_to area.name, area
       
  %td{"data-value" => area.priority, :id => "td_priority_#{area.id}"}
    %div{:id => "priority-button-#{area.id}"}
      = render :partial => "areas/priority_button", :locals => {:area_id => area.id}
           
  %td{"data-value" => area.writer_coverage, :id => "td_writer_coverage_#{area.id}"}
    %div{:id => "writer_coverage_button-#{area.id}"}
      = render :partial => "areas/writer_coverage_button", :locals => {:area_id => area.id}

  %td{"data-value" => area.support, :id => "td_support_#{area.id}"}
    %div{:id => "support-button-#{area.id}"}
      = render :partial => "areas/support_button", :locals => {:area_id => area.id}

  %td{:id => "area_burden_#{area.id}", "data-value" => area.burden}
    = burden_indicator(area)

  
  - if current_user.try(:super?)
    %td{:id => "td_destroy_#{area.id}"}
      = link_to edit_area_path(area), :class => "text-default" do
        %span.glyphicon.glyphicon-pencil
      &nbsp;
      &nbsp;
      = link_to area_path(area),  :method => :delete, :remote => true, :data =>  { confirm: "Really delete #{area.name}?" }, :class => "text-danger" do
        %span.glyphicon.glyphicon-remove

app/views/areas/_priority_button.html.haml
- levels = {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}
.btn-group.btn-group-xs
  != area_button(area_id,"Priority")
  - if current_user.try(:super?)
    %ul.dropdown-menu{:role => "menu"}
      - levels.each do |l,n|
        %li
          =link_to areas_set_area_priority_path(:area_id => area_id, :priority => n), :remote => true, :method => :post do
            = l

app/views/areas/_status_field.html.haml
- area = Area.find(area_id)
= support_indicator(area)

app/views/areas/_support_button.html.haml
- levels = {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}
.btn-group.btn-group-xs
  != area_button(area_id,"Support")
  - if current_user.try(:super?)
    %ul.dropdown-menu{:role => "menu"}
      - levels.each do |l,n|
        %li
          =link_to areas_set_area_support_path(:area_id => area_id, :support => n), :remote => true, :method => :post do
            = l

app/views/areas/_writer_coverage_button.html.haml
- levels = {"High" => 3, "Medium" => 2, "Low" => 1, "None" => 0}
.btn-group.btn-group-xs
  != area_button(area_id,"Coverage")
  - if current_user.try(:super?)
    %ul.dropdown-menu{:role => "menu"}
      - levels.each do |l,n|
        %li
          =link_to areas_set_writer_coverage_path(:area_id => area_id, :writer_coverage => n), :remote => true, :method => :post do
            = l

app/views/areas/destroy_area.js.haml
$("#area_row_#{area_id}").remove();

app/views/areas/edit.html.haml
- points = {"X-Small (1)" => 1, "Small (2)" => 2, "Medium (3)" => 3, "Large (5)" => 5, "X-Large (8)" => 8, "XX-Large (13)" => "13", "XXX-Large (20)" => "20"}



%h3.col-sm-offset-2
  = "Edit #{@area.name}"

%br
= form_for(@area, url: area_path(:area_id => @area.id),:html => {:class => "form-horizontal"} ) do |f|
  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, autofocus: true, :class => 'form-control'

  .form-group
    = f.label "Associated Writers", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.collection_select :user_ids, User.admins.order(:fullname), :id, :fullname, {}, {multiple: true, :class => 'form-control', "style" => "height:175px;" } 


  .form-group
    = f.label "Weekly Points Per Writer", :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.select(:points, points, {}, {class: "form-control"})
        
      
  .form-group
    = f.label :description, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_area :description, :class => 'form-control', :rows => 20
       
  .actions.col-sm-offset-2
    .col-sm-4
      = f.submit "Save", :class => 'btn btn-primary'


     

app/views/areas/new.html.haml
%h3.col-sm-offset-2
  New Area

%br
= form_for(@area, :html => {:class => "form-horizontal"} ) do |f|
  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-4
      = f.text_field :name, autofocus: true, :class => 'form-control'
        
  .actions.col-sm-offset-2
    .col-sm-4
      = f.submit "Create", :class => 'btn btn-primary'


     

app/views/areas/show.html.haml
%ol.breadcrumb
  %li
    = link_to "Home", root_path
  %li
    = link_to "Priority Areas", areas_path
  %li.active
    = @area.name
  - if current_user.try(:super?)
    %li
      = link_to edit_area_path(@area) do
        Edit
    
%h2
  = @area.name
    
- if @area.users.count > 0 
  %p.text-muted
    %span.glyphicon.glyphicon-user
    != @area.users.collect {|user| link_to user.handle, user}.to_sentence
  
!= @area.rendered_description


%hr

%h3
  = "Areas Similar to #{@area.name}"
.col-md-3
  %h4
    != "#{display_label(@area.priority, 'Priority')}"
  %ul.list-unstyled
    - Area.priority(@area.priority).each do |a|
      %li
        = link_to a.name, a
    
.col-md-3
  %h4
    != "#{display_label(@area.support_status, 'Risk')}"
  %ul.list-unstyled
    - Area.status(@area.support_status).each do |a|
      %li
        = link_to a.name, a

.col-md-3
  %h4
    != "#{burden_label(@area)}"
  %ul.list-unstyled
    - Area.cost(@area.burden).each do |a|
      %li
        = link_to a.name, a

.col-md-3
  %h4
    != "#{display_label(@area.writer_coverage, 'Coverage')}"
  %ul.list-unstyled
    - Area.cost(@area.burden).each do |a|
      %li
        = link_to a.name, a

app/views/areas/update_priority_button.js.haml
$("#priority-button-#{id}").html("#{j render(:partial => 'areas/priority_button', :locals => {:area_id => id})}");
$("#td_priority_#{id}").attr("data-value", "#{priority}");
$("#td_priority_#{id}").parent('tr').attr("data-priority", "#{priority}");
$("#priority-button-#{id}").effect("bounce",500);
$("#area_status_#{id}").html("#{j render(:partial => 'areas/status_field', :locals => {:area_id => id})}");
$("#area_status_#{id}").attr("data-value", "#{area.support_status}");
$("#area_burden_#{id}").attr("data-value", "#{area.burden}");

app/views/areas/update_support_button.js.haml
$("#support-button-#{id}").html("#{j render(:partial => 'areas/support_button', :locals => {:area_id => id})}");
$("#td_support_#{id}").attr("data-value", "#{support}");
$("#td_support_#{id}").parent('tr').attr("data-support", "#{support}");
$("#support-button-#{id}").effect("bounce",500);
$("#area_status_#{id}").html("#{j render(:partial => 'areas/status_field', :locals => {:area_id => id})}");
$("#area_burden_#{id}").html("#{j render(:partial => 'areas/burden_field', :locals => {:area_id => id})}");
$("#area_status_#{id}").attr("data-value", "#{area.support_status}");
$("#area_burden_#{id}").attr("data-value", "#{area.burden}");

app/views/areas/update_writer_coverage_button.js.haml
$("#writer_coverage_button-#{id}").html("#{j render(:partial => 'areas/writer_coverage_button', :locals => {:area_id => id})}");
$("#td_writer_coverage_#{id}").attr("data-value", "#{writer_coverage}");
$("#td_writer_coverage_#{id}").parent('tr').attr("data-writer_coverage", "#{writer_coverage}");
$("#writer_coverage_button-#{id}").effect("bounce",500);
$("#area_status_#{id}").html("#{j render(:partial => 'areas/status_field', :locals => {:area_id => id})}");
$("#area_burden_#{id}").html("#{j render(:partial => 'areas/burden_field', :locals => {:area_id => id})}");
$("#area_status_#{id}").attr("data-value", "#{area.support_status}");
$("#area_burden_#{id}").attr("data-value", "#{area.burden}");